[tool.poetry]
name = "scan"
version = "0.1.0"
description = "A project using CrewAI for orchestrating role-playing, autonomous AI agents."
authors = ["John Doe <john.doe@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
crewai = "^0.1.0"
duckduckgo-search = "^0.1.0"
langchain-google-genai = "^0.1.0"
python-dotenv = "^0.19.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
